[package]
name = "api"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
domain.workspace = true
application.workspace = true
infrastructure.workspace = true

strum.workspace = true
uuid.workspace = true
chrono.workspace = true
thiserror.workspace = true
tracing.workspace = true
derive-new.workspace = true
itertools.workspace = true
serde.workspace = true
